In [1]:
import pandas as pd

In [5]:
routes = pd.read_csv("../data/raw/airport_coordinates_20260819.csv")
routes.head()

  iata_code  latitude_deg  longitude_deg           timezone
0       EVV     38.036999     -87.532402    America/Chicago
1       CDV     60.491798    -145.477997  America/Anchorage
2       HDN     40.481201    -107.218002     America/Denver
3       JAC     43.607300    -110.737999     America/Denver
4       HPN     41.067001     -73.707603   America/New_York

In [6]:
len(routes)

351

In [3]:
names = pd.read_csv("/Users/nicholasstanfield/Documents/Codex/2026-09-01/referenced-chatgpt-conversation-this-is-an/outputs/airport_city_lookup.csv")
names.head()

,iata_code,municipality,display_label,airport_name,iso_region,iso_country,source_name,source_url
0,ABE,Allentown/Bethlehem,ABE (Allentown/Bethlehem),Lehigh Valley International Airport,US-PA,US,OurAirports,https://ourairports.com/airports/KABE/
1,ABI,Abilene,ABI (Abilene),Abilene Regional Airport,US-TX,US,OurAirports,https://ourairports.com/airports/KABI/
2,ABQ,Albuquerque,ABQ (Albuquerque),Albuquerque International Sunport,US-NM,US,OurAirports,https://ourairports.com/airports/KABQ/
3,ABR,Aberdeen,ABR (Aberdeen),Aberdeen Regional Airport,US-SD,US,OurAirports,https://ourairports.com/airports/KABR/
4,ABY,Albany,ABY (Albany),Southwest Georgia Regional Airport,US-GA,US,OurAirports,https://ourairports.com/airports/KABY/

In [7]:
len(names)

351

In [8]:
df = pd.merge(routes, names, on="iata_code")
len(df)

351

In [12]:
df = df.drop(columns=["iso_region", "iso_country", "source_name", "source_url"],axis=1)

In [13]:
df.isna().sum()

iata_code        0
latitude_deg     0
longitude_deg    0
timezone         0
municipality     0
display_label    0
airport_name     0
dtype: int64

In [14]:
df.to_csv("../data/processed/airport_information20260901.csv")